### ISSUE TITLE
Data-index deployment failed to start with image

### ISSUE THREAD

**Issue by masayag** [apache/incubator-kie-kogito-serverless-operator#342]
### Describe the bug

Using the following SonataflowPlatform CR to deploy DI and JS:
```
→ oc get sonataflowplatform -n sonataflow-infra -o yaml
apiVersion: v1
items:
- apiVersion: sonataflow.org/v1alpha08
  kind: SonataFlowPlatform
  metadata:
    annotations:
      meta.helm.sh/release-name: orchestrator
      meta.helm.sh/release-namespace: orchestrator
    creationTimestamp: "2024-01-09T10:55:09Z"
    generation: 2
    labels:
      app.kubernetes.io/managed-by: Helm
    name: sonataflow-platform
    namespace: sonataflow-infra
    resourceVersion: "39408746"
    uid: 6ca1122a-e03f-4458-98d7-eb56b0afb244
  spec:
    build:
      config:
        baseImage: quay.io/kiegroup/kogito-swf-builder-nightly:latest
        registry: {}
        strategy: platform
        strategyOptions:
          KanikoBuildCacheEnabled: "true"
          KanikoPersistentVolumeClaim: sonataflow-platform
        timeout: 5m0s
      template:
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 64Mi
        timeout: 0s
    devMode: {}
    services:
      dataIndex:
        enabled: true
        persistence:
          postgresql:
            secretRef:
              name: sonataflow-psql-postgresql
              passwordKey: postgres-password
              userKey: postgres-username
            serviceRef:
              name: sonataflow-psql-postgresql
              namespace: sonataflow-infra
        podTemplate:
          container:
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 512Mi
      jobService:
        enabled: true
        persistence:
          postgresql:
            secretRef:
              name: sonataflow-psql-postgresql
              passwordKey: postgres-password
              userKey: postgres-username
            serviceRef:
              name: sonataflow-psql-postgresql
              namespace: sonataflow-infra
        podTemplate:
          container:
            resources: {}
  status:
    cluster: openshift
    conditions:
    - lastUpdateTime: "2024-01-09T10:55:10Z"
      status: "True"
      type: Succeed
    info:
      goOS: linux
      goVersion: go1.19.9
    observedGeneration: 2
    version: "0.8"
kind: List
metadata:
  resourceVersion: ""
```
Ends with job-service running successfully, however, the data-index pod fails to start.

The image detected by the operator for DI is: `quay.io/kiegroup/kogito-data-index-postgresql:latest`
However, nightly image `quay.io/kiegroup/kogito-data-index-postgresql-nightly:latest` works nicely if specified specifically via
```
      podTemplate:
         container:
-          image: "quay.io/kiegroup/kogito-data-index-postgresql-nightly:latest"
```

### Expected behavior

The image for DI recommended by the operator should work.

### Actual behavior

The image detected by the operator for DI is: `quay.io/kiegroup/kogito-data-index-postgresql:latest`
```
→ oc logs -n sonataflow-infra deploy/sonataflow-platform-data-index-service -f
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-01-09 10:58:13,805 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.kogito.devservices.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-01-09 10:58:19,711 WARN  [io.qua.run.con.ConfigRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.devservices.enabled is set to 'false' but it is build time fixed to 'true'. Did you change the property quarkus.devservices.enabled after building the application?
2024-01-09 10:58:21,833 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 9.11.0 by Redgate
2024-01-09 10:58:21,834 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.11.0
2024-01-09 10:58:21,834 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) 
2024-01-09 10:58:23,416 INFO  [org.fly.cor.int.dat.bas.BaseDatabaseType] (main) Database: jdbc:postgresql://sonataflow-psql-postgresql.sonataflow-infra:5432/sonataflow (PostgreSQL 15.4)
2024-01-09 10:58:24,120 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [http-events-support]): org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Migration checksum mismatch for migration version 1.32.0
-> Applied to database : 1722286283
-> Resolved locally    : 1406353711
Either revert the changes to the migration, or run repair to update the schema history.
Migration checksum mismatch for migration version 1.44.0
-> Applied to database : 799676352
-> Resolved locally    : 1679365749
Either revert the changes to the migration, or run repair to update the schema history.
Detected applied migration not resolved locally: 1.45.0.0.
If you removed this migration intentionally, run repair to mark the migration as deleted.
Detected applied migration not resolved locally: 1.45.0.1.
If you removed this migration intentionally, run repair to mark the migration as deleted.
Detected applied migration not resolved locally: 1.45.0.2.
If you removed this migration intentionally, run repair to mark the migration as deleted.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:134)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:128)
	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:82)
	at io.quarkus.deployment.steps.FlywayProcessor$startActions1770701860.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.FlywayProcessor$startActions1770701860.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
```

### SonataFlow Operator version or git rev

`57b1f038ce9af5d92be1337fa7dbb9ea6730f524`

**Comment by ricardozanini** [comment]
@tchughesiv can you take a look?

**Comment by masayag** [comment]
@ricardozanini I'd like to close this one. I can't reproduce this issue anymore - seems it was fixed.
