### ISSUE TITLE
Workflow application is missing properties to post events to DataIndex service

### ISSUE THREAD

**Issue by dmartinol** [apache/incubator-kie-kogito-serverless-operator#348]
### Describe the bug

When the Data-Index service is generated by the `SonataFlowPlatform` instance, the workflow deployment is missing the  following application properties:

- `mp.messaging.outgoing.kogito-processinstances-events.connector` (set to `quarkus-http`)
- `mp.messaging.outgoing.kogito-processdefinitions-events.connector` (set to `quarkus-http`)
- `mp.messaging.outgoing.kogito-processdefinitions-events. url` (set to `<DATA)_INDEX_SERVICE_URL>/definitions`)

**Comment by masayag** [comment]
@jordigilh @wmedvede could you have a look at this issue?
Encountered when running a workflow against the latest version of the operator.

**Comment by masayag** [comment]
```
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec  java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/quarkus-run.jar 
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-01-11 08:32:35,122 mtaanalysis-7555744799-llzfj WARN  [io.quarkus.config:-1] (main) Unrecognized configuration key "kogito.events.processinstances.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-01-11 08:32:35,123 mtaanalysis-7555744799-llzfj WARN  [io.quarkus.config:-1] (main) Unrecognized configuration key "kogito.events.processdefinitions.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-01-11 08:32:35,123 mtaanalysis-7555744799-llzfj WARN  [io.quarkus.config:-1] (main) Unrecognized configuration key "kogito.events.usertasks.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-01-11 08:32:35,123 mtaanalysis-7555744799-llzfj WARN  [io.quarkus.config:-1] (main) Unrecognized configuration key "quarkus.container-image.build" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-01-11 08:32:35,124 mtaanalysis-7555744799-llzfj WARN  [io.quarkus.config:-1] (main) Unrecognized configuration key "kogito.events.variables.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-01-11 08:32:35,124 mtaanalysis-7555744799-llzfj WARN  [io.quarkus.config:-1] (main) Unrecognized configuration key "quarkus.container-image.group" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-01-11 08:32:35,125 mtaanalysis-7555744799-llzfj WARN  [io.quarkus.config:-1] (main) Unrecognized configuration key "kogito.data-index.blocking" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-01-11 08:32:35,125 mtaanalysis-7555744799-llzfj WARN  [io.quarkus.config:-1] (main) Unrecognized configuration key "kogito.data-index.domain-indexing" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-01-11 08:32:35,125 mtaanalysis-7555744799-llzfj WARN  [io.quarkus.config:-1] (main) Unrecognized configuration key "kogito.apps.persistence.type" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-01-11 08:32:35,126 mtaanalysis-7555744799-llzfj WARN  [io.quarkus.config:-1] (main) Unrecognized configuration key "kogito.jobs-service.url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-01-11 08:32:36,406 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (main) Detected a Linux x86_64 system
2024-01-11 08:32:36,424 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.DefaultPostgresBinaryResolver:-1] (main) Detected distribution: 'Red Hat Enterprise Linux'
2024-01-11 08:32:36,426 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.DefaultPostgresBinaryResolver:-1] (main) System specific postgres binaries found: 'postgres-linux-x86_64.txz'
2024-01-11 08:32:36,480 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (main) Extracting Postgres...
2024-01-11 08:32:38,603 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (main) Postgres binaries at /tmp/embedded-pg/PG-102e6363fced1e91aa3b6178e0d6f3a9
2024-01-11 08:32:38,631 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) The files belonging to this database system will be owned by user "1000730000".
2024-01-11 08:32:38,631 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) This user must also own the server process.
2024-01-11 08:32:38,631 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) 
2024-01-11 08:32:38,631 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) The database cluster will be initialized with locale "C.utf8".
2024-01-11 08:32:38,631 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) The default text search configuration will be set to "english".
2024-01-11 08:32:38,631 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) 
2024-01-11 08:32:38,631 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) Data page checksums are disabled.
2024-01-11 08:32:38,631 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) 
2024-01-11 08:32:38,631 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) fixing permissions on existing directory /tmp/epg8671805231243956436 ... ok
2024-01-11 08:32:38,632 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) creating subdirectories ... ok
2024-01-11 08:32:38,632 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) selecting dynamic shared memory implementation ... posix
2024-01-11 08:32:38,646 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) selecting default max_connections ... 100
2024-01-11 08:32:38,670 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) selecting default shared_buffers ... 128MB
2024-01-11 08:32:38,789 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) selecting default time zone ... UTC
2024-01-11 08:32:38,790 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) creating configuration files ... ok
2024-01-11 08:32:38,940 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) running bootstrap script ... ok
2024-01-11 08:32:39,546 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) performing post-bootstrap initialization ... ok
2024-01-11 08:32:39,564 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) syncing data to disk ... ok
2024-01-11 08:32:39,564 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) 
2024-01-11 08:32:39,564 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) Success. You can now start the database server using:
2024-01-11 08:32:39,564 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) 
2024-01-11 08:32:39,564 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93))     /tmp/embedded-pg/PG-102e6363fced1e91aa3b6178e0d6f3a9/bin/pg_ctl -D /tmp/epg8671805231243956436 -l logfile start
2024-01-11 08:32:39,564 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (initdb:pid(93)) 
2024-01-11 08:32:39,567 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (main) f3ccd6d2-162a-4338-aaf2-80785c60be92 initdb completed in 00:00:00.961
2024-01-11 08:32:39,571 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (main) f3ccd6d2-162a-4338-aaf2-80785c60be92 postmaster started as Process[pid=104, exitValue="not exited"] on port 40491.  Waiting up to PT10S for server startup to finish.
2024-01-11 08:32:39,615 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (postgres:pid(104)) waiting for server to start....2024-01-11 08:32:39.615 UTC [107] LOG:  starting PostgreSQL 14.8 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
2024-01-11 08:32:39,616 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (postgres:pid(104)) 2024-01-11 08:32:39.616 UTC [107] LOG:  listening on IPv6 address "::1", port 40491
2024-01-11 08:32:39,616 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (postgres:pid(104)) 2024-01-11 08:32:39.616 UTC [107] LOG:  listening on IPv4 address "127.0.0.1", port 40491
2024-01-11 08:32:39,616 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (postgres:pid(104)) 2024-01-11 08:32:39.616 UTC [107] LOG:  listening on Unix socket "/tmp/.s.PGSQL.40491"
2024-01-11 08:32:39,618 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (postgres:pid(104)) 2024-01-11 08:32:39.617 UTC [108] LOG:  database system was shut down at 2024-01-11 08:32:39 UTC
2024-01-11 08:32:39,621 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (postgres:pid(104)) 2024-01-11 08:32:39.620 UTC [107] LOG:  database system is ready to accept connections
2024-01-11 08:32:39,690 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (postgres:pid(104))  done
2024-01-11 08:32:39,690 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (postgres:pid(104)) server started
2024-01-11 08:32:39,773 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (main) f3ccd6d2-162a-4338-aaf2-80785c60be92 postmaster startup finished in 00:00:00.205
2024-01-11 08:32:39,773 mtaanalysis-7555744799-llzfj INFO  [io.quarkiverse.embedded.postgresql.EmbeddedPostgreSQLRecorder:-1] (main) Embedded Postgres started at port "40491" with database "postgres", user "postgres" and password "postgres"
2024-01-11 08:32:40,226 mtaanalysis-7555744799-llzfj WARN  [org.kie.kogito.addons.quarkus.knative.eventing.KnativeEventingConfigSourceFactory:-1] (main) K_SINK variable is empty or doesn't exist. Please make sure that this service is a Knative Source or has a SinkBinding bound to it.
2024-01-11 08:32:40,577 mtaanalysis-7555744799-llzfj WARN  [io.quarkus.agroal.runtime.AgroalConnectionConfigurer:-1] (main) Agroal does not support detecting if a connection is still usable after an exception for database kind: postgresql
2024-01-11 08:32:40,590 mtaanalysis-7555744799-llzfj WARN  [io.quarkus.agroal.runtime.AgroalConnectionConfigurer:-1] (main) Agroal does not support detecting if a connection is still usable after an exception for database kind: postgresql
2024-01-11 08:32:40,592 mtaanalysis-7555744799-llzfj WARN  [io.quarkus.agroal.runtime.AgroalConnectionConfigurer:-1] (main) Agroal does not support detecting if a connection is still usable after an exception for database kind: postgresql
2024-01-11 08:32:40,764 mtaanalysis-7555744799-llzfj INFO  [org.flywaydb.core.internal.license.VersionPrinter:-1] (main) Flyway Community Edition 9.11.0 by Redgate
2024-01-11 08:32:40,764 mtaanalysis-7555744799-llzfj INFO  [org.flywaydb.core.internal.license.VersionPrinter:-1] (main) See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.11.0
2024-01-11 08:32:40,764 mtaanalysis-7555744799-llzfj INFO  [org.flywaydb.core.internal.license.VersionPrinter:-1] (main) 
2024-01-11 08:32:40,832 mtaanalysis-7555744799-llzfj INFO  [org.flywaydb.core.internal.database.base.BaseDatabaseType:-1] (main) Database: jdbc:postgresql://localhost:40491/jobs_service (PostgreSQL 14.8)
2024-01-11 08:32:40,866 mtaanalysis-7555744799-llzfj INFO  [org.flywaydb.core.internal.command.DbValidate:-1] (main) Successfully validated 7 migrations (execution time 00:00.016s)
2024-01-11 08:32:40,877 mtaanalysis-7555744799-llzfj INFO  [org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory:-1] (main) Creating Schema History table "public"."flyway_schema_history" ...
2024-01-11 08:32:40,906 mtaanalysis-7555744799-llzfj INFO  [org.flywaydb.core.internal.command.DbMigrate:-1] (main) Current version of schema "public": << Empty Schema >>
2024-01-11 08:32:40,915 mtaanalysis-7555744799-llzfj INFO  [org.flywaydb.core.internal.command.DbMigrate:-1] (main) Migrating schema "public" to version "2.0.0 - Create Table"
2024-01-11 08:32:40,935 mtaanalysis-7555744799-llzfj INFO  [org.flywaydb.core.internal.command.DbMigrate:-1] (main) Migrating schema "public" to version "2.0.1 - job details increase job id size"
2024-01-11 08:32:40,946 mtaanalysis-7555744799-llzfj INFO  [org.flywaydb.core.internal.command.DbMigrate:-1] (main) Migrating schema "public" to version "2.0.2 - job details add fire time col"
2024-01-11 08:32:40,955 mtaanalysis-7555744799-llzfj INFO  [org.flywaydb.core.internal.command.DbMigrate:-1] (main) Migrating schema "public" to version "2.0.3 - Create Table Management"
2024-01-11 08:32:40,975 mtaanalysis-7555744799-llzfj INFO  [org.flywaydb.core.internal.command.DbMigrate:-1] (main) Migrating schema "public" to version "3.0.0 - Create Jobs Table V2"
2024-01-11 08:32:40,987 mtaanalysis-7555744799-llzfj INFO  [org.flywaydb.core.internal.command.DbMigrate:-1] (main) Migrating schema "public" to version "3.0.1 - Migrate Jobs v1 to v2 Table"
2024-01-11 08:32:40,994 mtaanalysis-7555744799-llzfj INFO  [org.flywaydb.core.internal.command.DbMigrate:-1] (main) Migrating schema "public" to version "3.0.2 - Add Execution Timeout Col"
2024-01-11 08:32:40,999 mtaanalysis-7555744799-llzfj INFO  [org.flywaydb.core.internal.command.DbMigrate:-1] (main) Successfully applied 7 migrations to schema "public", now at version v3.0.2 (execution time 00:00.099s)
2024-01-11 08:32:41,537 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (postgres:pid(104)) 2024-01-11 08:32:41.534 UTC [107] LOG:  received fast shutdown request
2024-01-11 08:32:41,537 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (postgres:pid(104)) 2024-01-11 08:32:41.535 UTC [107] LOG:  aborting any active transactions
2024-01-11 08:32:41,537 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (postgres:pid(104)) 2024-01-11 08:32:41.535 UTC [127] FATAL:  terminating connection due to administrator command
2024-01-11 08:32:41,537 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (postgres:pid(104)) 2024-01-11 08:32:41.535 UTC [129] FATAL:  terminating connection due to administrator command
2024-01-11 08:32:41,635 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (pg_ctl:pid(133)) waiting for server to shut down.... done
2024-01-11 08:32:41,635 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (pg_ctl:pid(133)) server stopped
2024-01-11 08:32:41,637 mtaanalysis-7555744799-llzfj INFO  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres:-1] (main) f3ccd6d2-162a-4338-aaf2-80785c60be92 shut down postmaster in 00:00:00.105
2024-01-11 08:32:41,833 mtaanalysis-7555744799-llzfj ERROR [io.quarkus.runtime.Application:-1] (main) Failed to start application (with profile [dev]): java.lang.IllegalArgumentException: SRMSG00071: Invalid channel configuration -  the `connector` attribute must be set for channel `kogito-processinstances-events`
	at io.smallrye.reactive.messaging.providers.impl.ConnectorConfig.lambda$new$0(ConnectorConfig.java:50)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.smallrye.reactive.messaging.providers.impl.ConnectorConfig.lambda$new$1(ConnectorConfig.java:50)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at io.smallrye.reactive.messaging.providers.impl.ConnectorConfig.<init>(ConnectorConfig.java:49)
	at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.lambda$extractConfigurationFor$0(ConfiguredChannelFactory.java:87)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.extractConfigurationFor(ConfiguredChannelFactory.java:76)
	at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:103)
	at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory_ClientProxy.initialize(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager.start(MediatorManager.java:206)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager_ClientProxy.start(Unknown Source)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:52)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_7f54e4b27c1b49e5e062caa58f1e82797fa01393.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:328)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:310)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:78)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
```
for a ConfigMap with the following properties:
```
quarkus.profile = prod
mta.endpoint = mta-openshift-mta.apps.ocp413.lab.local
mta.port = 443
mta.protocol = https
mta_url = ${mta.protocol}://${mta.endpoint}
quarkus.rest-client.mta_json.url = ${mta.protocol}://${mta.endpoint}:${mta.port}/hub
quarkus.kubernetes-client.devservices.enabled = false
kogito.events.processdefinitions.enabled = false
kogito.events.processinstances.enabled = true
kogito.events.usertasks.enabled = false
kogito.events.variables.enabled = false
mp.messaging.outgoing.kogito-job-service-job-request-events.connector = quarkus-http
mp.messaging.outgoing.kogito-job-service-job-request-events.url = http://sonataflow-platform-jobs-service.sonataflow-infra/v2/jobs/events
mp.messaging.outgoing.kogito-processinstances-events.url = http://sonataflow-platform-data-index-service.sonataflow-infra/processes
kogito.service.url = http://mtaanalysis.sonataflow-infra/
quarkus.http.port = 8080
quarkus.http.host = 0.0.0.0
org.kie.kogito.addons.knative.eventing.health-enabled = false
quarkus.devservices.enabled = false
quarkus.kogito.devservices.enabled = false
```

**Comment by dmartinol** [comment]
For the sake of completeness, if we add the missing feature to the properties ConfigMap, the application starts but doesn't seem to post process changes to the Data Index (graphQL query returns no data)

**Comment by wmedvede** [comment]
Hi @dmartinol which setup are you doing? I mean, how are you deploying the data-index.
The question is because as part of the OpenShift  usecase I'm preparing, that deploys both the data-index and jobs-service by using the sonataflow-platform, I can see that the operator is now generating this properties ni the workflow CM, which is good.
In fact, I can create a WF instance and see the expected information at the data-index and the jobs-service.

```
   kogito.events.usertasks.enabled = false

    kogito.events.variables.enabled = false

    kogito.events.processdefinitions.enabled = false

    kogito.service.url = http://callbackstatetimeouts.test-platform2-oc

    quarkus.http.port = 8080

    quarkus.http.host = 0.0.0.0

    org.kie.kogito.addons.knative.eventing.health-enabled = false

    quarkus.devservices.enabled = false

    quarkus.kogito.devservices.enabled = false

    kogito.events.processinstances.enabled = true

    mp.messaging.outgoing.kogito-job-service-job-request-events.connector =
    quarkus-http

    mp.messaging.outgoing.kogito-job-service-job-request-events.url =
    http://sonataflow-platform-jobs-service.test-platform2-oc/v2/jobs/events

    mp.messaging.outgoing.kogito-processinstances-events.url =
    http://sonataflow-platform-data-index-service.test-platform2-oc/processes
```

**Comment by dmartinol** [comment]
@wmedvede Data Index is deployed using SonataFlowPlatform as per these specs:
```yaml
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
  namespace: sonataflow-infra
spec:
  build:
    config:
      baseImage: quay.io/kiegroup/kogito-swf-builder-nightly:latest
      registry: {}
      strategy: platform
      strategyOptions:
        KanikoBuildCacheEnabled: "true"
        KanikoPersistentVolumeClaim: sonataflow-platform
      timeout: 5m0s
    template:
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 64Mi
      timeout: 0s
  devMode: {}
  services:
    dataIndex:
      enabled: true
      persistence:
        postgresql:
          secretRef:
            name: sonataflow-psql-postgresql
            passwordKey: postgres-password
            userKey: postgres-username
          serviceRef:
            name: sonataflow-psql-postgresql
            namespace: sonataflow-infra
      podTemplate:
        container:
          image: quay.io/kiegroup/kogito-data-index-postgresql-nightly:latest
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
    jobService:
      enabled: true
      persistence:
        postgresql:
          secretRef:
            name: sonataflow-psql-postgresql
            passwordKey: postgres-password
            userKey: postgres-username
          serviceRef:
            name: sonataflow-psql-postgresql
            namespace: sonataflow-infra
      podTemplate:
        container:
          image: quay.io/kiegroup/kogito-jobs-service-postgresql-nightly:latest
          resources: {}
```

**Comment by dmartinol** [comment]
@wmedvede according to today's findings, this issue is no more requested, unless we want to use it to temporary add the `processdefinitions.url` property automatically, and enable these events. WDYT?

**Comment by wmedvede** [comment]
This is being done here #353
