### ISSUE TITLE
Could not create index template in Elastic: java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by wmedvede** [apache/incubator-kie-kogito-serverless-operator#525]
### Describe the bug

From some point in time, the following error is being produced for example when we deploy a WF in preview mode.

**NOTE**: The workflow works fine, but the message is not good.

2024-09-04 13:01:41,777 ERROR [io.mic.ela.DefaultIndexTemplateCreator] (pool-5-thread-1) Could not create index template in Elastic: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:281)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1308)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1241)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1127)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1056)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1450)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1421)
	at io.micrometer.core.ipc.http.HttpUrlConnectionSender.send(HttpUrlConnectionSender.java:98)
	at io.micrometer.core.ipc.http.HttpSender$Request$Builder.send(HttpSender.java:306)
	at io.micrometer.elastic.DefaultIndexTemplateCreator.fetchIndexTemplateStatus(DefaultIndexTemplateCreator.java:61)
	at io.micrometer.elastic.ElasticMeterRegistry.attemptIndexTemplateCreation(ElasticMeterRegistry.java:164)
	at io.micrometer.elastic.ElasticMeterRegistry.createIndexTemplateIfNeeded(ElasticMeterRegistry.java:156)
	at io.micrometer.elastic.ElasticMeterRegistry.publish(ElasticMeterRegistry.java:117)
	at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafelyOrSkipIfInProgress(PushMeterRegistry.java:64)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

See the complete file here: https://gist.github.com/wmedvede/6f718af4eef21e90ac619ff888e8dbab

**Comment by ricardozanini** [comment]
Relates to this PR:

- https://github.com/apache/incubator-kie-tools/pull/2535

This library shouldn't be added to the builder image since it requires a fully functional elastic server available and a configuration set.

Only the`prometheus` and `monitoring` add-ons should suffice to scrape metrics for Prometheus. 

I'm investigating.
